// src/app/features/login/presentation/components/form.tsx

import { ChangeEventHandler } from 'react';

import { ControlsComponent } from 'app/shared/components';
import { UserForm } from '..';

type Props = {
    user: UserForm,
    isLoading: boolean,
    errors?: any,
    setValueField: ChangeEventHandler
};

const { InputComponent, ButtonSubmitComponent } = ControlsComponent;

export const FormComponent: React.FC<Props> = ({ user, isLoading, errors, setValueField }: Props) => {

    return (
        <>
            <InputComponent label='Correo electrónico' name='email'
                onChange={setValueField} type='email' value={user.email} error={errors.email} />

            <InputComponent label='Contraseña' name='password'
                onChange={setValueField} type='password' value={user.password} error={errors.password} />

            <ButtonSubmitComponent isLoading={isLoading} label='Iniciar Sesión' />
        </>
    );
};

// src/app/features/login/presentation/components/form.vue
<template>
  <div>
    <InputComponent
      label="Correo electrónico"
      name="email"
      :onChange="setValueField"
      type="email"
      :value="user.email"
      :error="errors.email"
    />

    <InputComponent
      label="Contraseña"
      name="password"
      :onChange="setValueField"
      type="password"
      :value="user.password"
      :error="errors.password"
    />

    <ButtonSubmitComponent
      class="btn-form"
      :isLoading="isLoading"
      label="Iniciar Sesión"
    />
  </div>
</template>

<script lang="ts">
import { UserForm } from "@/app/features/login/presentation/index.vue";
import { ControlsComponent } from "@/app/shared/components";
import { defineComponent, PropType, toRefs } from "vue";
const { InputComponent, ButtonSubmitComponent } = ControlsComponent;

export default defineComponent({
  name: "FormComponent",
  props: {
    user: {
      type: Object as PropType<UserForm>,
      required: true,
    },
    isLoading: {
      type: Boolean,
      required: true,
    },
    errors: {
      type: Object as PropType<UserForm>,
    },
    setValueField: {
      type: Function,
      required: true,
    },
  },
  components: {
    InputComponent,
    ButtonSubmitComponent,
  },
  setup(props) {
    return {
      ...toRefs(props),
    };
  },
});
</script>
<style scoped>
.btn-form {
  display: flex;
  flex-direction: row-reverse;
}
</style>
