// src/app/shared/components/controls/input.tsx
import TextField from '@material-ui/core/TextField/TextField';
import React, { ChangeEventHandler } from 'react';
import { JsxAttribute } from 'typescript';


type Props = {
    name: string,
    label: string,
    type: inputsType,
    value: string,
    error?: string,
    onChange: ChangeEventHandler,
    props?: JsxAttribute[]
};


type inputsType = 'text' | 'email' | 'password' | 'number'

export const InputComponent: React.FC<Props> = (_props: Props) => {

    const { name, label, type, value, error = null, onChange, props } = _props;

    return (
        <TextField
            variant='outlined'
            margin='dense'
            {...props}
            type={type}
            label={label}
            name={name}
            value={value}
            onChange={onChange}
            {...(error && { error: true, helperText: error })}
        />

    );
};

// src/app/shared/components/controls/input.vue
<template>
  <div class="field">
    <p class="control">
      <input
        class="input"
        :type="type"
        :placeholder="label"
        :value="value"
        :name="name"
        @input="onChange($event.target)"
      />
      <span>error:{{ error }}</span>
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

type inputsType = "text" | "email" | "password" | "number";

export default defineComponent({
  name: "InputComponent",
  props: {
    name: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
    },
    type: {
      type: String as PropType<inputsType>,
      required: true,
    },
    value: {
      type: String,
      required: true,
    },

    error: {
      type: String,
      default: "",
    },
    onChange: {
      type: Function,
      required: true,
    },
  },
  setup(props) {
    return {
      ...props,
    };
  },
});
</script>
